In [2]:
#############################################################################
#
#  csc531 Week5 -- Tutorial on Principal Component Analysis 
#  Week5_PCA.py ... written by Chakarida Nukoolkit (adapted from Dr.Jason Brownlee)
#            -- The sample code below do PCA to transform 4x5 --> 4x4  or 
#            from 5 columns, down to 4 columns...
#
#  Task 5-1 -- Step1 Run the given code below, then observe the result, 
#            especially the parameters of PCA and decomposition methods
#
#  Task 5-2 -- Make change to the array A to have more dimensions and 
#            more data, then try to do PCA to reduce it to 3, 2, and 1 component
#            Note !!! -- observe the resulted PCA and transformed data 
#            values and dimensions
#
##############################################################################
#
#  Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2, 3, 2, 5], [3, 4, 5, 7, 6], [6, 7, 8, 9, 14], [0, 1, 2, 3, 4]])
print()
print("A ... original")
print(A)
# create the PCA instance of 4 components
pca = PCA(4)
# performing PCA by fitting on data
pca.fit(A)

# access PCA values and vectors
print()
print("pca.components:")
print(pca.components_)
print("\npca.explained_variance:")
print(pca.explained_variance_)
print("\npca.explained_variance_ratio:")
print(pca.explained_variance_ratio_)

# transform data and print new data
B = pca.transform(A)
print("\nA after got transformed:")
print(B)



A ... original
[[ 1  2  3  2  5]
 [ 3  4  5  7  6]
 [ 6  7  8  9 14]
 [ 0  1  2  3  4]]

pca.components:
[[ 3.71816123e-01  3.71816123e-01  3.71816123e-01  4.35395209e-01
   6.29038412e-01]
 [ 8.28488650e-02  8.28488650e-02  8.28488650e-02  7.38904548e-01
  -6.58352691e-01]
 [-4.33845790e-01 -4.33845790e-01 -4.33845790e-01  5.14248074e-01
   4.13379258e-01]
 [ 8.08817317e-01 -3.07656861e-01 -5.01160457e-01  1.66533454e-16
   0.00000000e+00]]

pca.explained_variance:
[5.00188311e+01 2.45214417e+00 3.62358074e-01 6.89129744e-33]

pca.explained_variance_ratio:
[9.46728664e-01 4.64128234e-02 6.85851245e-03 1.30434652e-34]

A after got transformed:
[[-4.50354341e+00 -1.29296612e+00 -6.49103514e-01 -5.41233725e-16]
 [ 5.33367785e-01  2.24029712e+00 -2.67558628e-01  2.91433544e-16]
 [ 9.78281061e+00 -8.03075526e-01  1.63359471e-01  2.91433544e-16]
 [-5.81263498e+00 -1.44255475e-01  7.53302672e-01 -2.63677968e-16]]
